services:
  api:
    container_name: api
    image: cosmtrek/air
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - air_wd=/app
      - JOURNIAPI_DBHOST=db
      - JOURNIAPI_DBPASSWORD=dev
    volumes:
      - $PWD:/app

  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
