services:
  api:
    container_name: api
    image: cosmtrek/air
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - air_wd=/app
    volumes:
      - $PWD:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=journi
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgres:
